apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20240204043644.0.0+build.6aff574
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20240204043644.0.0+build.6aff574
  releaseNotes: |
    Release v20240204043644.0.0+build.6aff574 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-04-02-2024-00-43-25-243084092/where-for-dinner-my-apps-bundle@sha256:b269f55daaa8e54ace66612663230c8b0a68bee6a2506b03eb5567f518ef272e
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

